const Discord = require("discord.js");

module.exports = async (menu) => {      
  menu.reply.think(true);

  if (menu.values[0] === 'yay') {
      await menu.clicker.member.roles.add(conf.roles.yay)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.yay+"> rolü başarıyla verildi.")

}
  if (menu.values[0] === 'oğlak') {
      await menu.clicker.member.roles.add(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.oglak+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'kova') {
      await menu.clicker.member.roles.add(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.kova+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'balık') {
      await menu.clicker.member.roles.add(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.balik+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'aslan') {
      await menu.clicker.member.roles.add(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.aslan+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'başak') {
      await menu.clicker.member.roles.add(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.basak+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'terazi') {
      await menu.clicker.member.roles.add(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.terazi+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'akrep') {
      await menu.clicker.member.roles.add(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.akrep+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'koç') {
      await menu.clicker.member.roles.add(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.koc+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'boğa') {
      await menu.clicker.member.roles.add(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.boga+"> rolü başarıyla verildi.")
}
  if (menu.values[0] === 'yengeç') {
      await menu.clicker.member.roles.add(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.yengec+"> rolü başarıyla verildi.")
  
}
  if (menu.values[0] === 'ikizler') {
      await menu.clicker.member.roles.add(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit("Burç seçimin sonucunda <@&"+conf.roles.ikizler+"> rolü başarıyla verildi.")
}
    if (menu.values[0] === 'burctemizle') {
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
        menu.reply.edit("İsteğin sonucunda üzerindeki burç rolü alındı.")
}
   }; 
module.exports.config = {
    name: "clickMenu"
  }